
/* This is an automatically generated file, do not edit */

enum GENIVI_FUELSTOPADVISOR_Constants {
	GENIVI_FUELSTOPADVISOR_METRIC = 0x0010,
	GENIVI_FUELSTOPADVISOR_NON_METRIC = 0x0011,
	GENIVI_FUELSTOPADVISOR_ODOMETER = 0x0020,
	GENIVI_FUELSTOPADVISOR_FUEL_LEVEL = 0x0021,
	GENIVI_FUELSTOPADVISOR_TANK_DISTANCE = 0x0022,
	GENIVI_FUELSTOPADVISOR_INSTANT_FUEL_CONSUMPTION_PER_DISTANCE = 0x0023,
	GENIVI_FUELSTOPADVISOR_ENHANCED_TANK_DISTANCE = 0x0024,
	GENIVI_FUELSTOPADVISOR_DISTANCE = 0x0030,
	GENIVI_FUELSTOPADVISOR_TIME = 0x0031,
	GENIVI_FUELSTOPADVISOR_AVERAGE_FUEL_CONSUMPTION_PER_DISTANCE = 0x0032,
	GENIVI_FUELSTOPADVISOR_AVERAGE_SPEED = 0x0033,
};
  