#! /bin/bash
###########################################################################
# @licence app begin@
# SPDX-License-Identifier: MPL-2.0
#
# \copyright Copyright (C) 2016, PCA Peugeot Citroen
#
# \file step2: start fsa hmi
#
# \brief This file is part of the Build System.
#
# \author # Author: Philippe COLLIOT <philippe.colliot@mpsa.com>
#
# \version 1.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License (MPL), v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# For further information see http://www.genivi.org/.
#
# List of changes:
# 
#
# @licence end@
###########################################################################

CUR_DIR=$PWD
BIN_DIR=$CUR_DIR/build
SRC_DIR=$CUR_DIR

# location of exe, lib and config files
HMI_LAUNCHER=hmi-launcher
HMI_LAUNCHER_SRC_DIR=$SRC_DIR/hmi/qml/$HMI_LAUNCHER
HMI_LAUNCHER_BIN_DIR=$BIN_DIR/hmi/qml/$HMI_LAUNCHER
SCRIPT_DIR=$SRC_DIR/script
HMI_QML_DIR=$SRC_DIR/hmi/qml
app=$HMI_QML_DIR/application.qml # hmi panel launched by default
STYLE_SHEETS_GENERATED_INDICATOR=$HMI_QML_DIR/Core/style-sheets/the-style-sheets-have-been-generated-css.js

# check if style sheets have been generated
if [ ! -f $STYLE_SHEETS_GENERATED_INDICATOR ]
then
    echo "Please generate the style sheets before"
	$SCRIPT_DIR/prepare.sh -h
	exit 1
fi

# start the hmi 
$HMI_LAUNCHER_BIN_DIR/$HMI_LAUNCHER $app 

