#! /bin/bash
###########################################################################
# @licence app begin@
# SPDX-License-Identifier: MPL-2.0
#
# \copyright Copyright (C) 2016, PCA Peugeot Citroen
#
# \file step2: start enhanced position service
#
# \brief This file is part of the Build System.
#
# \author # Author: Philippe COLLIOT <philippe.colliot@mpsa.com>
#
# \version 1.0
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License (MPL), v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# For further information see http://www.genivi.org/.
#
# List of changes:
# 
#
# @licence end@
###########################################################################

CUR_DIR=$PWD
BIN_DIR=$CUR_DIR/build
SRC_DIR=$CUR_DIR
SCRIPT_DIR=$SRC_DIR/script

# location of exe, lib and config files
NAVIGATION=navigation
NAVIGATION_SRC_DIR=$SRC_DIR/$NAVIGATION/src/navigation
ENHANCED_POSITION_SERVICE=enhanced-position-service
ENHANCED_POSITION_SERVICE_SRC_DIR=$NAVIGATION_SRC_DIR/positioning/$ENHANCED_POSITION_SERVICE
ENHANCED_POSITION_SERVICE_BIN_DIR=$NAVIGATION_SRC_DIR/bin

# function to wait for the dbus service to be started, exit if too long
function wait_for_service
{
	for i in $(seq 1 50)
	do
		if dbus-send --dest=$1 $2 org.freedesktop.DBus.Introspectable.Introspect
		then
			return
		fi
		echo "Waiting for $1"
		sleep 0.1
	done
	exit 1
}

# start the  enhanced position service
$ENHANCED_POSITION_SERVICE_BIN_DIR/$ENHANCED_POSITION_SERVICE 
wait_for_service org.genivi.positioning.EnhancedPosition /org/genivi/positioning/EnhancedPosition

