#!/bin/sh
echo 'kill all remaining process created by step*'
for i in 1 2 3 4 5 6 7
do
STEP=$(pgrep -f step$i)
echo $STEP
if [ -n "$STEP" ]; then
	kill -TERM $(pgrep -P $(pgrep -o step$i))
	kill -TERM $(pgrep -o step$i)
fi
done

